use crate::model::JokerEdition;

use super::Joker;

impl Joker {
    pub fn get_edition(&self) -> JokerEdition {
        match self {
            Self::Joker { edition, .. }
            | Self::Greedy { edition, .. }
            | Self::Lusty { edition, .. }
            | Self::Wrathful { edition, .. }
            | Self::Gluttonous { edition, .. }
            | Self::Jolly { edition, .. }
            | Self::Zany { edition, .. }
            | Self::Mad { edition, .. }
            | Self::Crazy { edition, .. }
            | Self::Droll { edition, .. }
            | Self::Sly { edition, .. }
            | Self::Wily { edition, .. }
            | Self::Clever { edition, .. }
            | Self::Devious { edition, .. }
            | Self::Crafty { edition, .. }
            | Self::Half { edition, .. }
            | Self::Stencil { edition, .. }
            | Self::Fingers { edition, .. }
            | Self::Mime { edition, .. }
            | Self::Credit { edition, .. }
            | Self::Dagger { edition, .. }
            | Self::Banner { edition, .. }
            | Self::Mystic { edition, .. }
            | Self::Marble { edition, .. }
            | Self::Loyalty { edition, .. }
            | Self::Ball { edition, .. }
            | Self::Misprint { edition, .. }
            | Self::Dusk { edition, .. }
            | Self::Fist { edition, .. }
            | Self::Chaos { edition, .. }
            | Self::Fibonacci { edition, .. }
            | Self::Steel { edition, .. }
            | Self::Scary { edition, .. }
            | Self::Abstract { edition, .. }
            | Self::Gratification { edition, .. }
            | Self::Hack { edition, .. }
            | Self::Pareidolia { edition, .. }
            | Self::Michel { edition, .. }
            | Self::Steven { edition, .. }
            | Self::Todd { edition, .. }
            | Self::Scholar { edition, .. }
            | Self::Business { edition, .. }
            | Self::Supernova { edition, .. }
            | Self::Bus { edition, .. }
            | Self::Space { edition, .. }
            | Self::Egg { edition, .. }
            | Self::Burglar { edition, .. }
            | Self::Blackboard { edition, .. }
            | Self::Runner { edition, .. }
            | Self::Cream { edition, .. }
            | Self::Dna { edition, .. }
            | Self::Splash { edition, .. }
            | Self::Blue { edition, .. }
            | Self::Sixth { edition, .. }
            | Self::Constellation { edition, .. }
            | Self::Hiker { edition, .. }
            | Self::Faceless { edition, .. }
            | Self::Green { edition, .. }
            | Self::Superposition { edition, .. }
            | Self::List { edition, .. }
            | Self::Cavendish { edition, .. }
            | Self::Sharp { edition, .. }
            | Self::Red { edition, .. }
            | Self::Madness { edition, .. }
            | Self::Square { edition, .. }
            | Self::Seance { edition, .. }
            | Self::Riff { edition, .. }
            | Self::Vampire { edition, .. }
            | Self::Shortcut { edition, .. }
            | Self::Hologram { edition, .. }
            | Self::Vagabond { edition, .. }
            | Self::Baron { edition, .. }
            | Self::Cloud { edition, .. }
            | Self::Rocket { edition, .. }
            | Self::Obelisk { edition, .. }
            | Self::Midas { edition, .. }
            | Self::Luchador { edition, .. }
            | Self::Photograph { edition, .. }
            | Self::Gift { edition, .. }
            | Self::Turtle { edition, .. }
            | Self::Erosion { edition, .. }
            | Self::Parking { edition, .. }
            | Self::Rebate { edition, .. }
            | Self::Moon { edition, .. }
            | Self::Hallucination { edition, .. }
            | Self::Fortune { edition, .. }
            | Self::Juggler { edition, .. }
            | Self::Drunkard { edition, .. }
            | Self::Stone { edition, .. }
            | Self::Golden { edition, .. }
            | Self::Lucky { edition, .. }
            | Self::Baseball { edition, .. }
            | Self::Bull { edition, .. }
            | Self::Cola { edition, .. }
            | Self::Trading { edition, .. }
            | Self::Flash { edition, .. }
            | Self::Popcorn { edition, .. }
            | Self::Trousers { edition, .. }
            | Self::Ancient { edition, .. }
            | Self::Ramen { edition, .. }
            | Self::Walkie { edition, .. }
            | Self::Seltzer { edition, .. }
            | Self::Castle { edition, .. }
            | Self::Smiley { edition, .. }
            | Self::Campfire { edition, .. }
            | Self::Ticket { edition, .. }
            | Self::Bones { edition, .. }
            | Self::Acrobat { edition, .. }
            | Self::Sock { edition, .. }
            | Self::Swashbuckler { edition, .. }
            | Self::Troubadour { edition, .. }
            | Self::Certificate { edition, .. }
            | Self::Smeared { edition, .. }
            | Self::Throwback { edition, .. }
            | Self::Chad { edition, .. }
            | Self::Gem { edition, .. }
            | Self::Bloodstone { edition, .. }
            | Self::Arrowhead { edition, .. }
            | Self::Onyx { edition, .. }
            | Self::Glass { edition, .. }
            | Self::Showman { edition, .. }
            | Self::Flower { edition, .. }
            | Self::Blueprint { edition, .. }
            | Self::Wee { edition, .. }
            | Self::Andy { edition, .. }
            | Self::Oops { edition, .. }
            | Self::Idol { edition, .. }
            | Self::Double { edition, .. }
            | Self::Matador { edition, .. }
            | Self::Road { edition, .. }
            | Self::Duo { edition, .. }
            | Self::Trio { edition, .. }
            | Self::Family { edition, .. }
            | Self::Order { edition, .. }
            | Self::Tribe { edition, .. }
            | Self::Stuntman { edition, .. }
            | Self::Invisible { edition, .. }
            | Self::Brainstorm { edition, .. }
            | Self::Satellite { edition, .. }
            | Self::Shoot { edition, .. }
            | Self::License { edition, .. }
            | Self::Cartomancer { edition, .. }
            | Self::Astronomer { edition, .. }
            | Self::Burnt { edition, .. }
            | Self::Bootstraps { edition, .. }
            | Self::Canio { edition, .. }
            | Self::Triboulet { edition, .. }
            | Self::Yorick { edition, .. }
            | Self::Chicot { edition, .. }
            | Self::Perkeo { edition, .. } => *edition,
        }
    }

    pub fn change_edition(&mut self, new: JokerEdition) {
        match self {
            Self::Joker { edition, .. }
            | Self::Greedy { edition, .. }
            | Self::Lusty { edition, .. }
            | Self::Wrathful { edition, .. }
            | Self::Gluttonous { edition, .. }
            | Self::Jolly { edition, .. }
            | Self::Zany { edition, .. }
            | Self::Mad { edition, .. }
            | Self::Crazy { edition, .. }
            | Self::Droll { edition, .. }
            | Self::Sly { edition, .. }
            | Self::Wily { edition, .. }
            | Self::Clever { edition, .. }
            | Self::Devious { edition, .. }
            | Self::Crafty { edition, .. }
            | Self::Half { edition, .. }
            | Self::Stencil { edition, .. }
            | Self::Fingers { edition, .. }
            | Self::Mime { edition, .. }
            | Self::Credit { edition, .. }
            | Self::Dagger { edition, .. }
            | Self::Banner { edition, .. }
            | Self::Mystic { edition, .. }
            | Self::Marble { edition, .. }
            | Self::Loyalty { edition, .. }
            | Self::Ball { edition, .. }
            | Self::Misprint { edition, .. }
            | Self::Dusk { edition, .. }
            | Self::Fist { edition, .. }
            | Self::Chaos { edition, .. }
            | Self::Fibonacci { edition, .. }
            | Self::Steel { edition, .. }
            | Self::Scary { edition, .. }
            | Self::Abstract { edition, .. }
            | Self::Gratification { edition, .. }
            | Self::Hack { edition, .. }
            | Self::Pareidolia { edition, .. }
            | Self::Michel { edition, .. }
            | Self::Steven { edition, .. }
            | Self::Todd { edition, .. }
            | Self::Scholar { edition, .. }
            | Self::Business { edition, .. }
            | Self::Supernova { edition, .. }
            | Self::Bus { edition, .. }
            | Self::Space { edition, .. }
            | Self::Egg { edition, .. }
            | Self::Burglar { edition, .. }
            | Self::Blackboard { edition, .. }
            | Self::Runner { edition, .. }
            | Self::Cream { edition, .. }
            | Self::Dna { edition, .. }
            | Self::Splash { edition, .. }
            | Self::Blue { edition, .. }
            | Self::Sixth { edition, .. }
            | Self::Constellation { edition, .. }
            | Self::Hiker { edition, .. }
            | Self::Faceless { edition, .. }
            | Self::Green { edition, .. }
            | Self::Superposition { edition, .. }
            | Self::List { edition, .. }
            | Self::Cavendish { edition, .. }
            | Self::Sharp { edition, .. }
            | Self::Red { edition, .. }
            | Self::Madness { edition, .. }
            | Self::Square { edition, .. }
            | Self::Seance { edition, .. }
            | Self::Riff { edition, .. }
            | Self::Vampire { edition, .. }
            | Self::Shortcut { edition, .. }
            | Self::Hologram { edition, .. }
            | Self::Vagabond { edition, .. }
            | Self::Baron { edition, .. }
            | Self::Cloud { edition, .. }
            | Self::Rocket { edition, .. }
            | Self::Obelisk { edition, .. }
            | Self::Midas { edition, .. }
            | Self::Luchador { edition, .. }
            | Self::Photograph { edition, .. }
            | Self::Gift { edition, .. }
            | Self::Turtle { edition, .. }
            | Self::Erosion { edition, .. }
            | Self::Parking { edition, .. }
            | Self::Rebate { edition, .. }
            | Self::Moon { edition, .. }
            | Self::Hallucination { edition, .. }
            | Self::Fortune { edition, .. }
            | Self::Juggler { edition, .. }
            | Self::Drunkard { edition, .. }
            | Self::Stone { edition, .. }
            | Self::Golden { edition, .. }
            | Self::Lucky { edition, .. }
            | Self::Baseball { edition, .. }
            | Self::Bull { edition, .. }
            | Self::Cola { edition, .. }
            | Self::Trading { edition, .. }
            | Self::Flash { edition, .. }
            | Self::Popcorn { edition, .. }
            | Self::Trousers { edition, .. }
            | Self::Ancient { edition, .. }
            | Self::Ramen { edition, .. }
            | Self::Walkie { edition, .. }
            | Self::Seltzer { edition, .. }
            | Self::Castle { edition, .. }
            | Self::Smiley { edition, .. }
            | Self::Campfire { edition, .. }
            | Self::Ticket { edition, .. }
            | Self::Bones { edition, .. }
            | Self::Acrobat { edition, .. }
            | Self::Sock { edition, .. }
            | Self::Swashbuckler { edition, .. }
            | Self::Troubadour { edition, .. }
            | Self::Certificate { edition, .. }
            | Self::Smeared { edition, .. }
            | Self::Throwback { edition, .. }
            | Self::Chad { edition, .. }
            | Self::Gem { edition, .. }
            | Self::Bloodstone { edition, .. }
            | Self::Arrowhead { edition, .. }
            | Self::Onyx { edition, .. }
            | Self::Glass { edition, .. }
            | Self::Showman { edition, .. }
            | Self::Flower { edition, .. }
            | Self::Blueprint { edition, .. }
            | Self::Wee { edition, .. }
            | Self::Andy { edition, .. }
            | Self::Oops { edition, .. }
            | Self::Idol { edition, .. }
            | Self::Double { edition, .. }
            | Self::Matador { edition, .. }
            | Self::Road { edition, .. }
            | Self::Duo { edition, .. }
            | Self::Trio { edition, .. }
            | Self::Family { edition, .. }
            | Self::Order { edition, .. }
            | Self::Tribe { edition, .. }
            | Self::Stuntman { edition, .. }
            | Self::Invisible { edition, .. }
            | Self::Brainstorm { edition, .. }
            | Self::Satellite { edition, .. }
            | Self::Shoot { edition, .. }
            | Self::License { edition, .. }
            | Self::Cartomancer { edition, .. }
            | Self::Astronomer { edition, .. }
            | Self::Burnt { edition, .. }
            | Self::Bootstraps { edition, .. }
            | Self::Canio { edition, .. }
            | Self::Triboulet { edition, .. }
            | Self::Yorick { edition, .. }
            | Self::Chicot { edition, .. }
            | Self::Perkeo { edition, .. } => *edition = new,
        }
    }
}
