use super::Joker;

impl Joker {
    pub fn get_sell_value(&self) -> usize {
        match self {
            Self::Joker { sell_value, .. }
            | Self::Greedy { sell_value, .. }
            | Self::Lusty { sell_value, .. }
            | Self::Wrathful { sell_value, .. }
            | Self::Gluttonous { sell_value, .. }
            | Self::Jolly { sell_value, .. }
            | Self::Zany { sell_value, .. }
            | Self::Mad { sell_value, .. }
            | Self::Crazy { sell_value, .. }
            | Self::Droll { sell_value, .. }
            | Self::Sly { sell_value, .. }
            | Self::Wily { sell_value, .. }
            | Self::Clever { sell_value, .. }
            | Self::Devious { sell_value, .. }
            | Self::Crafty { sell_value, .. }
            | Self::Half { sell_value, .. }
            | Self::Stencil { sell_value, .. }
            | Self::Fingers { sell_value, .. }
            | Self::Mime { sell_value, .. }
            | Self::Credit { sell_value, .. }
            | Self::Dagger { sell_value, .. }
            | Self::Banner { sell_value, .. }
            | Self::Mystic { sell_value, .. }
            | Self::Marble { sell_value, .. }
            | Self::Loyalty { sell_value, .. }
            | Self::Ball { sell_value, .. }
            | Self::Misprint { sell_value, .. }
            | Self::Dusk { sell_value, .. }
            | Self::Fist { sell_value, .. }
            | Self::Chaos { sell_value, .. }
            | Self::Fibonacci { sell_value, .. }
            | Self::Steel { sell_value, .. }
            | Self::Scary { sell_value, .. }
            | Self::Abstract { sell_value, .. }
            | Self::Gratification { sell_value, .. }
            | Self::Hack { sell_value, .. }
            | Self::Pareidolia { sell_value, .. }
            | Self::Michel { sell_value, .. }
            | Self::Steven { sell_value, .. }
            | Self::Todd { sell_value, .. }
            | Self::Scholar { sell_value, .. }
            | Self::Business { sell_value, .. }
            | Self::Supernova { sell_value, .. }
            | Self::Bus { sell_value, .. }
            | Self::Space { sell_value, .. }
            | Self::Egg { sell_value, .. }
            | Self::Burglar { sell_value, .. }
            | Self::Blackboard { sell_value, .. }
            | Self::Runner { sell_value, .. }
            | Self::Cream { sell_value, .. }
            | Self::Dna { sell_value, .. }
            | Self::Splash { sell_value, .. }
            | Self::Blue { sell_value, .. }
            | Self::Sixth { sell_value, .. }
            | Self::Constellation { sell_value, .. }
            | Self::Hiker { sell_value, .. }
            | Self::Faceless { sell_value, .. }
            | Self::Green { sell_value, .. }
            | Self::Superposition { sell_value, .. }
            | Self::List { sell_value, .. }
            | Self::Cavendish { sell_value, .. }
            | Self::Sharp { sell_value, .. }
            | Self::Red { sell_value, .. }
            | Self::Madness { sell_value, .. }
            | Self::Square { sell_value, .. }
            | Self::Seance { sell_value, .. }
            | Self::Riff { sell_value, .. }
            | Self::Vampire { sell_value, .. }
            | Self::Shortcut { sell_value, .. }
            | Self::Hologram { sell_value, .. }
            | Self::Vagabond { sell_value, .. }
            | Self::Baron { sell_value, .. }
            | Self::Cloud { sell_value, .. }
            | Self::Rocket { sell_value, .. }
            | Self::Obelisk { sell_value, .. }
            | Self::Midas { sell_value, .. }
            | Self::Luchador { sell_value, .. }
            | Self::Photograph { sell_value, .. }
            | Self::Gift { sell_value, .. }
            | Self::Turtle { sell_value, .. }
            | Self::Erosion { sell_value, .. }
            | Self::Parking { sell_value, .. }
            | Self::Rebate { sell_value, .. }
            | Self::Moon { sell_value, .. }
            | Self::Hallucination { sell_value, .. }
            | Self::Fortune { sell_value, .. }
            | Self::Juggler { sell_value, .. }
            | Self::Drunkard { sell_value, .. }
            | Self::Stone { sell_value, .. }
            | Self::Golden { sell_value, .. }
            | Self::Lucky { sell_value, .. }
            | Self::Baseball { sell_value, .. }
            | Self::Bull { sell_value, .. }
            | Self::Cola { sell_value, .. }
            | Self::Trading { sell_value, .. }
            | Self::Flash { sell_value, .. }
            | Self::Popcorn { sell_value, .. }
            | Self::Trousers { sell_value, .. }
            | Self::Ancient { sell_value, .. }
            | Self::Ramen { sell_value, .. }
            | Self::Walkie { sell_value, .. }
            | Self::Seltzer { sell_value, .. }
            | Self::Castle { sell_value, .. }
            | Self::Smiley { sell_value, .. }
            | Self::Campfire { sell_value, .. }
            | Self::Ticket { sell_value, .. }
            | Self::Bones { sell_value, .. }
            | Self::Acrobat { sell_value, .. }
            | Self::Sock { sell_value, .. }
            | Self::Swashbuckler { sell_value, .. }
            | Self::Troubadour { sell_value, .. }
            | Self::Certificate { sell_value, .. }
            | Self::Smeared { sell_value, .. }
            | Self::Throwback { sell_value, .. }
            | Self::Chad { sell_value, .. }
            | Self::Gem { sell_value, .. }
            | Self::Bloodstone { sell_value, .. }
            | Self::Arrowhead { sell_value, .. }
            | Self::Onyx { sell_value, .. }
            | Self::Glass { sell_value, .. }
            | Self::Showman { sell_value, .. }
            | Self::Flower { sell_value, .. }
            | Self::Blueprint { sell_value, .. }
            | Self::Wee { sell_value, .. }
            | Self::Andy { sell_value, .. }
            | Self::Oops { sell_value, .. }
            | Self::Idol { sell_value, .. }
            | Self::Double { sell_value, .. }
            | Self::Matador { sell_value, .. }
            | Self::Road { sell_value, .. }
            | Self::Duo { sell_value, .. }
            | Self::Trio { sell_value, .. }
            | Self::Family { sell_value, .. }
            | Self::Order { sell_value, .. }
            | Self::Tribe { sell_value, .. }
            | Self::Stuntman { sell_value, .. }
            | Self::Invisible { sell_value, .. }
            | Self::Brainstorm { sell_value, .. }
            | Self::Satellite { sell_value, .. }
            | Self::Shoot { sell_value, .. }
            | Self::License { sell_value, .. }
            | Self::Cartomancer { sell_value, .. }
            | Self::Astronomer { sell_value, .. }
            | Self::Burnt { sell_value, .. }
            | Self::Bootstraps { sell_value, .. }
            | Self::Canio { sell_value, .. }
            | Self::Triboulet { sell_value, .. }
            | Self::Yorick { sell_value, .. }
            | Self::Chicot { sell_value, .. }
            | Self::Perkeo { sell_value, .. } => *sell_value,
        }
    }

    pub fn increase_sell_value(&mut self) {
        match self {
            Self::Joker { sell_value, .. }
            | Self::Greedy { sell_value, .. }
            | Self::Lusty { sell_value, .. }
            | Self::Wrathful { sell_value, .. }
            | Self::Gluttonous { sell_value, .. }
            | Self::Jolly { sell_value, .. }
            | Self::Zany { sell_value, .. }
            | Self::Mad { sell_value, .. }
            | Self::Crazy { sell_value, .. }
            | Self::Droll { sell_value, .. }
            | Self::Sly { sell_value, .. }
            | Self::Wily { sell_value, .. }
            | Self::Clever { sell_value, .. }
            | Self::Devious { sell_value, .. }
            | Self::Crafty { sell_value, .. }
            | Self::Half { sell_value, .. }
            | Self::Stencil { sell_value, .. }
            | Self::Fingers { sell_value, .. }
            | Self::Mime { sell_value, .. }
            | Self::Credit { sell_value, .. }
            | Self::Dagger { sell_value, .. }
            | Self::Banner { sell_value, .. }
            | Self::Mystic { sell_value, .. }
            | Self::Marble { sell_value, .. }
            | Self::Loyalty { sell_value, .. }
            | Self::Ball { sell_value, .. }
            | Self::Misprint { sell_value, .. }
            | Self::Dusk { sell_value, .. }
            | Self::Fist { sell_value, .. }
            | Self::Chaos { sell_value, .. }
            | Self::Fibonacci { sell_value, .. }
            | Self::Steel { sell_value, .. }
            | Self::Scary { sell_value, .. }
            | Self::Abstract { sell_value, .. }
            | Self::Gratification { sell_value, .. }
            | Self::Hack { sell_value, .. }
            | Self::Pareidolia { sell_value, .. }
            | Self::Michel { sell_value, .. }
            | Self::Steven { sell_value, .. }
            | Self::Todd { sell_value, .. }
            | Self::Scholar { sell_value, .. }
            | Self::Business { sell_value, .. }
            | Self::Supernova { sell_value, .. }
            | Self::Bus { sell_value, .. }
            | Self::Space { sell_value, .. }
            | Self::Egg { sell_value, .. }
            | Self::Burglar { sell_value, .. }
            | Self::Blackboard { sell_value, .. }
            | Self::Runner { sell_value, .. }
            | Self::Cream { sell_value, .. }
            | Self::Dna { sell_value, .. }
            | Self::Splash { sell_value, .. }
            | Self::Blue { sell_value, .. }
            | Self::Sixth { sell_value, .. }
            | Self::Constellation { sell_value, .. }
            | Self::Hiker { sell_value, .. }
            | Self::Faceless { sell_value, .. }
            | Self::Green { sell_value, .. }
            | Self::Superposition { sell_value, .. }
            | Self::List { sell_value, .. }
            | Self::Cavendish { sell_value, .. }
            | Self::Sharp { sell_value, .. }
            | Self::Red { sell_value, .. }
            | Self::Madness { sell_value, .. }
            | Self::Square { sell_value, .. }
            | Self::Seance { sell_value, .. }
            | Self::Riff { sell_value, .. }
            | Self::Vampire { sell_value, .. }
            | Self::Shortcut { sell_value, .. }
            | Self::Hologram { sell_value, .. }
            | Self::Vagabond { sell_value, .. }
            | Self::Baron { sell_value, .. }
            | Self::Cloud { sell_value, .. }
            | Self::Rocket { sell_value, .. }
            | Self::Obelisk { sell_value, .. }
            | Self::Midas { sell_value, .. }
            | Self::Luchador { sell_value, .. }
            | Self::Photograph { sell_value, .. }
            | Self::Gift { sell_value, .. }
            | Self::Turtle { sell_value, .. }
            | Self::Erosion { sell_value, .. }
            | Self::Parking { sell_value, .. }
            | Self::Rebate { sell_value, .. }
            | Self::Moon { sell_value, .. }
            | Self::Hallucination { sell_value, .. }
            | Self::Fortune { sell_value, .. }
            | Self::Juggler { sell_value, .. }
            | Self::Drunkard { sell_value, .. }
            | Self::Stone { sell_value, .. }
            | Self::Golden { sell_value, .. }
            | Self::Lucky { sell_value, .. }
            | Self::Baseball { sell_value, .. }
            | Self::Bull { sell_value, .. }
            | Self::Cola { sell_value, .. }
            | Self::Trading { sell_value, .. }
            | Self::Flash { sell_value, .. }
            | Self::Popcorn { sell_value, .. }
            | Self::Trousers { sell_value, .. }
            | Self::Ancient { sell_value, .. }
            | Self::Ramen { sell_value, .. }
            | Self::Walkie { sell_value, .. }
            | Self::Seltzer { sell_value, .. }
            | Self::Castle { sell_value, .. }
            | Self::Smiley { sell_value, .. }
            | Self::Campfire { sell_value, .. }
            | Self::Ticket { sell_value, .. }
            | Self::Bones { sell_value, .. }
            | Self::Acrobat { sell_value, .. }
            | Self::Sock { sell_value, .. }
            | Self::Swashbuckler { sell_value, .. }
            | Self::Troubadour { sell_value, .. }
            | Self::Certificate { sell_value, .. }
            | Self::Smeared { sell_value, .. }
            | Self::Throwback { sell_value, .. }
            | Self::Chad { sell_value, .. }
            | Self::Gem { sell_value, .. }
            | Self::Bloodstone { sell_value, .. }
            | Self::Arrowhead { sell_value, .. }
            | Self::Onyx { sell_value, .. }
            | Self::Glass { sell_value, .. }
            | Self::Showman { sell_value, .. }
            | Self::Flower { sell_value, .. }
            | Self::Blueprint { sell_value, .. }
            | Self::Wee { sell_value, .. }
            | Self::Andy { sell_value, .. }
            | Self::Oops { sell_value, .. }
            | Self::Idol { sell_value, .. }
            | Self::Double { sell_value, .. }
            | Self::Matador { sell_value, .. }
            | Self::Road { sell_value, .. }
            | Self::Duo { sell_value, .. }
            | Self::Trio { sell_value, .. }
            | Self::Family { sell_value, .. }
            | Self::Order { sell_value, .. }
            | Self::Tribe { sell_value, .. }
            | Self::Stuntman { sell_value, .. }
            | Self::Invisible { sell_value, .. }
            | Self::Brainstorm { sell_value, .. }
            | Self::Satellite { sell_value, .. }
            | Self::Shoot { sell_value, .. }
            | Self::License { sell_value, .. }
            | Self::Cartomancer { sell_value, .. }
            | Self::Astronomer { sell_value, .. }
            | Self::Burnt { sell_value, .. }
            | Self::Bootstraps { sell_value, .. }
            | Self::Canio { sell_value, .. }
            | Self::Triboulet { sell_value, .. }
            | Self::Yorick { sell_value, .. }
            | Self::Chicot { sell_value, .. }
            | Self::Perkeo { sell_value, .. } => *sell_value += 1,
        }
    }
}
