[package]
name = "balatro-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
dotenvy = "0.15.7"
rand = "0.9.0"
serde_json = "1.0.140"
sqlx = { version = "0.8.3", features = ["postgres"] }
strum = { version = "0.27.1", features = ["derive"] }
tokio = "1.44.1"
