create type card_rank as enum ('ace', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'jack', 'queen', 'king');
create type card_suit as enum ('spade', 'heart', 'club', 'diamond');
create type card_enhancement as enum ('bonus', 'mult', 'wild', 'glass', 'steel', 'stone', 'gold', 'lucky');
create type card_edition as enum ('base', 'foil', 'holographic', 'polychrome');
create type card_seal as enum ('gold', 'red', 'blue', 'purple');
create type joker_edition as enum ('base', 'foil', 'holographic', 'polychrome', 'negative');
create type joker as enum ('Joker', 'Greedy Joker', 'Lusty Joker', 'Wrathful Joker', 'Gluttonous Joker', 'Jolly Joker', 'Zany Joker', 'Mad Joker', 'Crazy Joker', 'Droll Joker', 'Sly Joker', 'Wily Joker', 'Clever Joker', 'Devious Joker', 'Crafty Joker', 'Half Joker', 'Joker Stencil', 'Four Fingers', 'Mime', 'Credit Card', 'Ceremonial Dagger', 'Banner', 'Mystic Summit', 'Marble Joker', 'Loyalty Card', '8 Ball', 'Misprint', 'Dusk', 'Raised Fist', 'Chaos the Clown', 'Fibonacci', 'Steel Joker', 'Scary Face', 'Abstract Joker', 'Delayed Gratification', 'Hack', 'Pareidolia', 'Gros Michel', 'Even Steven', 'Odd Todd', 'Scholar', 'Business Card', 'Supernova', 'Ride the Bus', 'Space Joker', 'Egg', 'Burglar', 'Blackboard', 'Runner', 'Ice Cream', 'DNA', 'Splash', 'Blue Joker', 'Sixth Sense', 'Constellation', 'Hiker', 'Faceless Joker', 'Green Joker', 'Superposition', 'To Do List', 'Cavendish', 'Card Sharp', 'Red Card', 'Madness', 'Square Joker', 'Seance', 'Riff-Raff', 'Vampire', 'Shortcut', 'Hologram', 'Vagabond', 'Baron', 'Cloud 9', 'Rocket', 'Obelisk', 'Midas Mask', 'Luchador', 'Photograph', 'Gift Card', 'Turtle Bean', 'Erosion', 'Reserved Parking', 'Mail-In Rebate', 'To the Moon', 'Hallucination', 'Fortune Teller', 'Juggler', 'Drunkard', 'Stone Joker', 'Golden Joker', 'Lucky Cat', 'Baseball Card', 'Bull', 'Diet Cola', 'Trading Card', 'Flash Card', 'Popcorn', 'Spare Trousers', 'Ancient Joker', 'Ramen', 'Walkie Talkie', 'Seltzer', 'Castle', 'Smiley Face', 'Campfire', 'Golden Ticket', 'Mr. Bones', 'Acrobat', 'Sock and Buskin', 'Swashbuckler', 'Troubadour', 'Certificate', 'Smeared Joker', 'Throwback', 'Hanging Chad', 'Rough Gem', 'Bloodstone', 'Arrowhead', 'Onyx Agate', 'Glass Joker', 'Showman', 'Flower Pot', 'Blueprint', 'Wee Joker', 'Merry Andy', 'Oops! All 6s', 'The Idol', 'Seeing Double', 'Matador', 'Hit the Road', 'The Duo', 'The Trio', 'The Family', 'The Order', 'The Tribe', 'Stuntman', 'Invisible Joker', 'Brainstorm', 'Satellite', 'Shoot the Moon', 'Drivers License', 'Cartomancer', 'Astronomer', 'Burnt Joker', 'Bootstraps', 'Canio', 'Tribulet', 'Yorick', 'Chicot', 'Perkeo');
create type consumable as enum ('The Fool', 'The Magician', 'The High Prestess', 'The Empress', 'The Emperor', 'The Hierophant', 'The Lovers', 'The Chariot', 'Justice', 'The Hermit', 'The Wheel of Fortune', 'Strength', 'The Hanged Man', 'Death', 'Temperance', 'The Devil', 'The Tower', 'The Star', 'The Moon', 'The Sun', 'Judgement', 'The World', 'Pluto', 'Mercury', 'Uranus', 'Venus', 'Saturn', 'Jupiter', 'Earth', 'Mars', 'Neptune', 'Planet X', 'Ceres', 'Eris', 'Familiar', 'Grim', 'Incantation', 'Talisman', 'Aura', 'Wraith', 'Sigil', 'Ouija', 'Ectoplasm', 'Immolate', 'Ankh', 'Deja Vu', 'Hex', 'Trance', 'Medium', 'Cryptid', 'The Soul', 'Black Hole');
CREATE TYPE public.hand_type AS ENUM ('high card', 'pair', 'two pair', 'three of a kind', 'straight', 'flush', 'full house', 'four of a kind', 'straight flush', 'five of a kind', 'flush house', 'flush five');
